// app/src/app/Components/shared-components/forms-automator/form-fields/hidden-input.component.tsx
import { ICommonFormEleProps } from 'app/Components/shared-components/forms-automator/form-automator.types'
import React, { memo } from 'react'

export const HiddenInput: React.FC<ICommonFormEleProps> = memo(function HiddenInput ({ formEle, element, handleChange }: ICommonFormEleProps) {
  if (element[formEle.fieldName] === undefined || element[formEle.fieldName] === null) {
    element[formEle.fieldName] = ''
  }

  return (<input
    key={formEle.fieldName}
    name={formEle.fieldName}
    type="hidden"
    value={element[formEle.fieldName]}
    onChange={(event: React.ChangeEvent<HTMLInputElement>) => handleChange(formEle.fieldName, event.target.value)}
          />)
}, (prevProps, nextProps) => prevProps.element[prevProps.formEle.fieldName] === nextProps.element[nextProps.formEle.fieldName])

// app/src/app/ui/shared-components/forms-automator/form-fields/hidden-input/hidden-input.component.ts
import { Component, Input } from '@angular/core';
import { FormGroup } from '@angular/forms';
import { AbstractElement } from '@anita/client/ui/shared-components/forms-automator/form-fields/abstract-element';
import { HiddenInput } from '@anita/client/ui/shared-components/forms-automator/form-fields/form-fields-model';

@Component({
  selector: 'app-hidden-input',
  templateUrl: './hidden-input.component.html'
})
export class HiddenInputComponent {

  @Input()
  public formEle: HiddenInput<AbstractElement>;

  @Input()
  public formData: FormGroup;

}

<div *ngIf="formData" [formGroup]="formData">
  <input type="hidden" [formControlName]="formEle['fieldName']">
</div>
